export const SELECT_VALUE = "SELECT_VALUE"
export const SUBMIT_QUERY  = "SUBMIT_QUERY"

//API
export const FETCH_GENRE_BEGIN = "FETCH_GENRE_BEGIN"
export const FETCH_GENRE_SUCCESS = "FETCH_GENRE_SUCCESS"
export const FETCH_GENRE_FAILURE = "FETCH_GENRE_FAILURE"